name: Build and Test

on:
  push:
    branches: [ main, testing ]
    paths-ignore: 
      - '**.md'
  pull_request:
    branches: [ main, testing ]
    paths-ignore: 
      - '**.md'

jobs:
  build:

    runs-on: windows-latest
    env:
      SA_PASSWORD: NotASecret!12

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
      env:
        NUGET_AUTH_TOKEN: RequiredButNotUsed
    - name: NuGet Restore
      run: dotnet restore --verbosity normal
    - name: Build
      run: dotnet build
    - name: Setup SQL Server container
      run: test/setup.ps1
      shell: pwsh
    - name: Durable framework tests
      run: dotnet test --no-build --verbosity normal ./test/DurableTask.SqlServer.Tests/DurableTask.SqlServer.Tests.csproj
    - name: Functions runtime tests
      run: dotnet test --no-build --verbosity normal ./test/DurableTask.SqlServer.AzureFunctions.Tests/DurableTask.SqlServer.AzureFunctions.Tests.csproj
